from pathlib import Path

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt

SUPPORTED_IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg"}


def set_document_defaults(document):
    section = document.sections[0]
    section.top_margin = Inches(0.7)
    section.bottom_margin = Inches(0.7)
    section.left_margin = Inches(0.7)
    section.right_margin = Inches(0.7)

    styles = document.styles
    normal = styles["Normal"]
    normal.font.name = "Arial"
    normal.font.size = Pt(10)

    for style_name in ["Heading 1", "Heading 2", "Heading 3"]:
        style = styles[style_name]
        style.font.name = "Arial"
        style.font.bold = True


def add_branding_image(document, settings):
    path_value = settings.get("report_branding", {}).get("patch_image_path", "").strip()
    if not path_value:
        return

    image_path = Path(path_value)
    if not image_path.exists() or not image_path.is_file():
        return

    if image_path.suffix.lower() not in SUPPORTED_IMAGE_EXTENSIONS:
        return

    try:
        paragraph = document.add_paragraph()
        paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
        paragraph.add_run().add_picture(str(image_path), width=Inches(1.1))
    except Exception:
        return


def add_key_value_table(document, rows):
    table = document.add_table(rows=0, cols=2)
    table.style = "Table Grid"
    for label, value in rows:
        cells = table.add_row().cells
        cells[0].text = str(label)
        cells[1].text = str(value or "")
    document.add_paragraph()


def add_bullets(document, values):
    if values:
        for value in values:
            document.add_paragraph(str(value), style="List Bullet")
    else:
        document.add_paragraph("None selected.")


def add_text_section(document, heading, text):
    document.add_heading(heading, level=1)
    document.add_paragraph(text or "")


def add_evidence_items(document, items):
    document.add_heading("Evidence / Device Items", level=1)

    if not items:
        document.add_paragraph("No evidence/device items listed.")
        return

    for index, item in enumerate(items, start=1):
        document.add_heading(f"Item {index}", level=2)
        add_key_value_table(document, [
            ("Item Number", item.get("item_number", "")),
            ("Evidence Number", item.get("evidence_number", "")),
            ("Device / Media Type", item.get("device_or_media_type", "")),
            ("Make / Model", item.get("make_model", "")),
            ("Serial Number", item.get("serial_number", "")),
            ("IMEI / MEID", item.get("imei_meid", "")),
            ("Phone Number", item.get("phone_number", "")),
            ("Storage Capacity", item.get("storage_capacity", "")),
            ("Condition Received", item.get("condition_received", "")),
            ("Power / Lock State", item.get("power_lock_state", "")),
            ("Passcode / Password Provided", item.get("passcode_provided", "")),
            ("Known Account Info", item.get("known_account_info", "")),
            ("Item Notes", item.get("item_notes", "")),
        ])


def build_docx_request(packet, settings):
    document = Document()
    set_document_defaults(document)
    add_branding_image(document, settings)

    agency = packet.get("agency", {})
    case_info = packet.get("case_info", {})
    investigator = packet.get("investigator_info", {})
    authority = packet.get("legal_authority", {})
    scope = packet.get("scope", {})
    items = packet.get("evidence_items", [])
    details = packet.get("request_details", {})
    priority = packet.get("priority_info", {})
    handoff = packet.get("handoff_info", {})
    options = packet.get("report_options", {})

    title = document.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run("DIGITAL FORENSICS REQUEST PACKET")
    run.bold = True
    run.font.size = Pt(16)

    if agency.get("agency_name") or agency.get("unit_name"):
        paragraph = document.add_paragraph()
        paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
        if agency.get("agency_name"):
            paragraph.add_run(agency.get("agency_name", ""))
        if agency.get("agency_name") and agency.get("unit_name"):
            paragraph.add_run("\n")
        if agency.get("unit_name"):
            paragraph.add_run(agency.get("unit_name", ""))

    document.add_paragraph()

    document.add_heading("Request Information", level=1)
    add_key_value_table(document, [
        ("Generated By", f"{packet.get('app_name', '')} v{packet.get('app_version', '')}"),
        ("Created At", packet.get("created_at", "")),
        ("Schema", f"{packet.get('schema_name', '')} v{packet.get('schema_version', '')}"),
    ])

    document.add_heading("Case Information", level=1)
    add_key_value_table(document, [
        ("Case Number", case_info.get("case_number", "")),
        ("Agency Case Number", case_info.get("agency_case_number", "")),
        ("Offense / Incident Type", case_info.get("offense_type", "")),
    ])

    document.add_heading("Submitting Investigator", level=1)
    add_key_value_table(document, [
        ("Submitting Agency", investigator.get("submitting_agency", "")),
        ("Submitting Unit", investigator.get("submitting_unit", "")),
        ("Submitting Investigator", investigator.get("submitting_investigator", "")),
        ("Phone", investigator.get("investigator_phone", "")),
        ("Email", investigator.get("investigator_email", "")),
        ("Supervisor", investigator.get("supervisor", "")),
    ])

    document.add_heading("Legal Authority", level=1)
    add_key_value_table(document, [
        ("Authority Type", authority.get("authority_type", "")),
        ("Authority Date", authority.get("authority_date", "")),
        ("Authority Reference / Document Number", authority.get("authority_reference", "")),
        ("Authority Notes", authority.get("authority_notes", "")),
    ])

    document.add_heading("Legal Authority / Scope Options", level=1)
    add_bullets(document, scope.get("scope_options", []))

    document.add_heading("Scope Limitations", level=1)
    add_key_value_table(document, [
        ("Date Range Limited", "Yes" if scope.get("date_range_limited") else "No"),
        ("Authorized Date Range", scope.get("authorized_date_range", "")),
        ("Specific Apps / Platforms Limited", "Yes" if scope.get("specific_apps_limited") else "No"),
        ("Authorized Apps / Platforms", scope.get("authorized_apps_platforms", "")),
        ("Specific Accounts Limited", "Yes" if scope.get("specific_accounts_limited") else "No"),
        ("Authorized Accounts", scope.get("authorized_accounts", "")),
        ("Keyword Limited", "Yes" if scope.get("keyword_limited") else "No"),
        ("Authorized Keywords", scope.get("authorized_keywords", "")),
        ("Additional Scope Notes", scope.get("scope_notes", "")),
    ])

    add_evidence_items(document, items)

    document.add_heading("Requested Forensic Actions", level=1)
    add_bullets(document, details.get("requested_actions", []))

    add_text_section(document, "Investigative Objective / Requested Information", details.get("investigative_objective", ""))
    add_text_section(document, "Known Facts / Context for Examiner", details.get("known_facts_for_examiner", ""))

    document.add_heading("Priority / Urgency", level=1)
    add_key_value_table(document, [
        ("Priority", priority.get("priority", "")),
        ("Requested Due Date", priority.get("requested_due_date", "")),
    ])
    document.add_paragraph("Urgency Flags:")
    add_bullets(document, priority.get("urgency_flags", []))
    add_text_section(document, "Priority Notes", priority.get("priority_notes", ""))

    document.add_heading("Submission / Handoff", level=1)
    add_key_value_table(document, [
        ("Transfer Method", handoff.get("transfer_method", "")),
        ("Packaging / Seal Information", handoff.get("packaging_seal_info", "")),
        ("Handoff Notes", handoff.get("handoff_notes", "")),
    ])

    document.add_heading("Important Scope Note", level=1)
    document.add_paragraph(packet.get("disclaimer", ""))

    if options.get("include_acknowledgement_block"):
        document.add_heading("Submission Acknowledgement", level=1)
        add_key_value_table(document, [
            ("Submitted By", investigator.get("submitting_investigator", "")),
            ("Date", ""),
        ])
        document.add_paragraph("Submitting Investigator Signature: _______________________________")
        document.add_paragraph()
        document.add_paragraph("Received By: _______________________________")
        document.add_paragraph("Receiving Staff Signature: _______________________________")
        document.add_paragraph("Date / Time Received: _______________________________")

    document.add_paragraph()
    end = document.add_paragraph("End of Digital Forensics Request Packet")
    end.alignment = WD_ALIGN_PARAGRAPH.CENTER
    return document


def save_docx_request(packet, settings, docx_path):
    document = build_docx_request(packet, settings)
    document.save(docx_path)
    return docx_path